# Generated by Django 2.1.7 on 2020-05-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200502_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
