# Generated by Django 2.1.7 on 2020-05-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200504_1541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes_total',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
